"""
Утилиты для создания человеко-читаемых экспортов артефактов
"""

import json
from pathlib import Path
from typing import Dict, Any, List
from datetime import datetime


def export_human_readable(
    artifact_data: Dict[str, Any],
    step_name: str,
    output_dir: Path,
    metadata: Dict[str, Any] = None
) -> Path:
    """
    Создает человеко-читаемую версию артефакта.
    
    Args:
        artifact_data: Данные артефакта
        step_name: Имя шага
        output_dir: Директория для сохранения
        metadata: Дополнительные метаданные
    
    Returns:
        Путь к созданному файлу
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Создаем имя файла
    filename = f"{step_name}_HUMAN_READABLE.md"
    output_path = output_dir / filename
    
    # Извлекаем метаданные из артефакта
    artifact_metadata = artifact_data.get("__metadata", {})
    
    # Создаем markdown контент
    content = _generate_human_readable_content(
        artifact_data, step_name, artifact_metadata, metadata
    )
    
    # Сохраняем файл
    output_path.write_text(content, encoding='utf-8')
    
    return output_path


def _generate_human_readable_content(
    data: Dict[str, Any],
    step_name: str,
    artifact_metadata: Dict[str, Any],
    additional_metadata: Dict[str, Any] = None
) -> str:
    """Генерирует содержимое human-readable файла."""
    
    # Заголовок
    content = [f"# {step_name.upper()} - Human Readable Export"]
    content.append("")
    
    # Метаданные
    content.append("## 📋 Metadata")
    content.append("")
    
    # Метаданные из артефакта
    if artifact_metadata:
        content.append("### Standard Information")
        content.append(f"- **Standard ID**: {artifact_metadata.get('standard_id', 'N/A')}")
        content.append(f"- **Source Path**: {artifact_metadata.get('source_path', 'N/A')}")
        content.append(f"- **Fingerprint**: `{artifact_metadata.get('fingerprint', 'N/A')[:16]}...`")
        content.append(f"- **Timestamp**: {artifact_metadata.get('timestamp', 'N/A')}")
        content.append("")
    
    # Дополнительные метаданные
    if additional_metadata:
        content.append("### Execution Information")
        for key, value in additional_metadata.items():
            content.append(f"- **{key.replace('_', ' ').title()}**: {value}")
        content.append("")
    
    # Сводка данных
    content.append("## 📊 Data Summary")
    content.append("")
    
    # Подсчитываем поля
    data_fields = [k for k in data.keys() if not k.startswith('__')]
    content.append(f"- **Total Fields**: {len(data_fields)}")
    content.append(f"- **Data Keys**: {', '.join(data_fields)}")
    content.append("")
    
    # Специфичный контент для разных типов шагов
    if step_name.startswith("step_03"):
        content.extend(_format_interview_content(data))
    elif step_name.startswith("step_04"):
        content.extend(_format_jtbd_content(data))
    elif step_name.startswith("step_05"):
        content.extend(_format_segments_content(data))
    elif step_name.startswith("step_06"):
        content.extend(_format_decision_mapping_content(data))
    else:
        content.extend(_format_generic_content(data))
    
    # Полные данные
    content.append("## 🔍 Full Data (JSON)")
    content.append("")
    content.append("```json")
    content.append(json.dumps(data, indent=2, ensure_ascii=False))
    content.append("```")
    content.append("")
    
    # Футер
    content.append("---")
    content.append("*Generated by AI Marketing Agent*")
    content.append(f"*Timestamp: {datetime.now().isoformat()}*")
    
    return "\n".join(content)


def _format_interview_content(data: Dict[str, Any]) -> List[str]:
    """Форматирует контент для интервью."""
    content = []
    
    # Статистика интервью
    interviews = data.get("interviews", [])
    if interviews:
        content.append("### Interview Statistics")
        content.append(f"- **Total Interviews**: {len(interviews)}")
        
        # Группировка по персонам
        personas = {}
        for interview in interviews:
            persona = interview.get("persona", "Unknown")
            personas[persona] = personas.get(persona, 0) + 1
        
        content.append("- **Personas Distribution**:")
        for persona, count in personas.items():
            content.append(f"  - {persona}: {count} interviews")
        content.append("")
    
    return content


def _format_jtbd_content(data: Dict[str, Any]) -> List[str]:
    """Форматирует контент для JTBD."""
    content = []
    
    # Статистика JTBD
    jobs = data.get("jobs", [])
    if jobs:
        content.append("### JTBD Statistics")
        content.append(f"- **Total Jobs**: {len(jobs)}")
        
        # Группировка по типам
        job_types = {}
        for job in jobs:
            job_type = job.get("type", "Unknown")
            job_types[job_type] = job_types.get(job_type, 0) + 1
        
        content.append("- **Job Types Distribution**:")
        for job_type, count in job_types.items():
            content.append(f"  - {job_type}: {count} jobs")
        content.append("")
    
    return content


def _format_segments_content(data: Dict[str, Any]) -> List[str]:
    """Форматирует контент для сегментов."""
    content = []
    
    # Статистика сегментов
    segments = data.get("segments", [])
    if segments:
        content.append("### Segments Statistics")
        content.append(f"- **Total Segments**: {len(segments)}")
        
        # Группировка по приоритету
        priorities = {}
        for segment in segments:
            priority = segment.get("priority", "Unknown")
            priorities[priority] = priorities.get(priority, 0) + 1
        
        content.append("- **Priority Distribution**:")
        for priority, count in priorities.items():
            content.append(f"  - Priority {priority}: {count} segments")
        content.append("")
    
    return content


def _format_decision_mapping_content(data: Dict[str, Any]) -> List[str]:
    """Форматирует контент для карт решений."""
    content = []
    
    # Статистика карт решений
    decision_maps = data.get("decision_maps", [])
    if decision_maps:
        content.append("### Decision Maps Statistics")
        content.append(f"- **Total Decision Maps**: {len(decision_maps)}")
        content.append("")
    
    return content


def _format_generic_content(data: Dict[str, Any]) -> List[str]:
    """Форматирует контент для общих шагов."""
    content = []
    
    # Общая статистика
    content.append("### General Statistics")
    content.append(f"- **Data Structure**: {type(data).__name__}")
    
    # Подсчитываем вложенные объекты
    nested_objects = 0
    for value in data.values():
        if isinstance(value, (dict, list)):
            nested_objects += 1
    
    content.append(f"- **Nested Objects**: {nested_objects}")
    content.append("")
    
    return content


def export_multiple_human_readable(
    artifacts: Dict[str, Dict[str, Any]],
    output_dir: Path,
    metadata: Dict[str, Any] = None
) -> List[Path]:
    """
    Создает human-readable версии для нескольких артефактов.
    
    Args:
        artifacts: Словарь {step_name: artifact_data}
        output_dir: Директория для сохранения
        metadata: Дополнительные метаданные
    
    Returns:
        Список путей к созданным файлам
    """
    created_files = []
    
    for step_name, artifact_data in artifacts.items():
        try:
            file_path = export_human_readable(
                artifact_data, step_name, output_dir, metadata
            )
            created_files.append(file_path)
        except Exception as e:
            print(f"Error creating human-readable for {step_name}: {e}")
    
    return created_files


def create_human_readable_index(
    created_files: List[Path],
    output_dir: Path
) -> Path:
    """
    Создает индексный файл со ссылками на все human-readable экспорты.
    
    Args:
        created_files: Список путей к созданным файлам
        output_dir: Директория для сохранения
    
    Returns:
        Путь к индексному файлу
    """
    index_path = output_dir / "HUMAN_READABLE_INDEX.md"
    
    content = ["# Human Readable Exports Index"]
    content.append("")
    content.append(f"Generated: {datetime.now().isoformat()}")
    content.append("")
    content.append("## Available Exports")
    content.append("")
    
    for file_path in sorted(created_files):
        relative_path = file_path.relative_to(output_dir)
        step_name = file_path.stem.replace("_HUMAN_READABLE", "")
        content.append(f"- [{step_name}]({relative_path})")
    
    content.append("")
    content.append("---")
    content.append("*Generated by AI Marketing Agent*")
    
    index_path.write_text("\n".join(content), encoding='utf-8')
    
    return index_path

