# Project Configuration: my-saas
# Override default settings for this specific project

project:
  name: "my-saas"
  version: "1.0.0"
  description: "SaaS product JTBD analysis project"

workflow:
  # Override default workflow steps if needed
  custom_steps: []
  
  # Quality thresholds for this project
  quality_threshold: 0.8
  max_reflection_loops: 3

analysis:
  # Analysis type: frequency or sequential
  type: "frequency"
  
  # Collection method: simulation or userboard
  method: "simulation"
  
  # Custom personas for this project
  personas:
    - id: "startup_founder"
      profile: "a startup founder looking for cost-effective SaaS solutions"
      priority: "high"
    - id: "enterprise_manager"
      profile: "an enterprise manager focused on scalability and security"
      priority: "medium"
    - id: "freelancer"
      profile: "a freelancer who needs flexible, affordable tools"
      priority: "low"

output:
  # Output format preferences
  include_raw_data: true
  generate_summary: true
  export_formats: ["json", "md"]
